// CommonJS, every files is module (by default)
// Modules - Encapsutated Code (only share minium)

const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
require('./7-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)